### ISSUE TITLE
Converter bug on ios test

### ISSUE THREAD

**Issue by Link184** [Foso/Ktorfit#830]
### Ktorfit version

2.3.0 - 2.4.0

### What happened and how can we reproduce this issue?

I have a SuspendResponseConverter exactly how it is shown in the documentation https://foso.github.io/Ktorfit/converters/suspendresponseconverter/

The bug happens only when we run ios test and only where generic responses are used, like List<>
Seems like there is a issue in the TypeInfo ktor logic.

Steps to reproduce:
Unzip the [provided archive](https://github.com/user-attachments/files/19210847/Ktorfitbug.zip)

Run `MyServiceTest` on ios target.

Note: If we use the deprecated `TypeInfo` api everything works.
To see how deprecated api works just follow the instructions from `ResultResponseConverterFactory` line 31.
Seems like one parameter in TypeInfo constructor is not used anymore but the bug still happens if we don't pass it 🧙 

### What did you expect to happen?

ios tests must finish gracefully

### Is there anything else we need to know about?

TypeData that you provide in `Converter.SuspendResponseConverter.convert()` has different structures in 2.2.0 and (2.3.0 & 2.4.0):
2.4.0:
```
typeArgs=[
	TypeData(qualifiedName=, typeArgs=[], typeInfo=TypeInfo(class kotlin.collections.List), isNullable=false)
], 
typeInfo=TypeInfo(kotlin.Result<kotlin.collections.List<MyModel>>), isNullable=false)
```

2.2.0
```
typeArgs=[
	TypeData(qualifiedName=, typeArgs=[
		TypeData(qualifiedName=, typeArgs=[], typeInfo=TypeInfo(MyModel), isNullable=false)
	], 
	typeInfo=TypeInfo(kotlin.collections.List<MyModel>), isNullable=false)
], 
typeInfo=TypeInfo(kotlin.Result<kotlin.collections.List<MyModel>>), isNullable=false)
```

**Comment by Foso** [comment]
This is fixed with 2.4.1

**Comment by Link184** [comment]
> This is fixed with 2.4.1

@Foso nope, the issue is still there with 2.4.1.
If I update the library in the sample project I provided to you I can see the same error

**Comment by Link184** [comment]
Looks like https://github.com/Link184/Ktorfit/blob/5bd6f2f277eb83d6db5bdafb428a6fcc7e1579c0/ktorfit-lib-core/src/jvmTest/kotlin/de/jensklingenberg/ktorfit/converter/ConverterFactoryTest.kt can catch this error but it is located in jvm sourceSet, and on jvm we don't have this bug 🐛  . 

Would be great to have it in commonTest, not sure if ksp works with commonTest source set... maybe a new gradle module designed only for integration tests may work 🤔

**Comment by Foso** [comment]
Hi, please try 2.5.0, it's using the deprecated TypeInfo again

**Comment by Foso** [comment]
@Link184 Can you try if 2.5.0 also works for you?
